force-app/main/default/objects/Http_Event__e/Http_Event__e.object-meta.xml
<CustomObject>
    <label>Http Event</label>
    <pluralLabel>Http Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Http_Life_Cycle__c/Http_Life_Cycle__c.object-meta.xml
<CustomObject>
    <label>Http Life Cycle</label>
    <nameField>
        <label>Http Life Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Http Life Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Http_Life_Cycle__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Http_Life_Cycle__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/HttpEventTriggerHandler.cls
/**
 * Created by AntonAntoniuk on 25.09.2019.
 */

public with sharing class HttpEventTriggerHandler {

    public HttpEventTriggerHandler() {
    }

    public void setHttpRecords(List<Http_Event__e> events) {
        List<Http_Life_Cycle__c> httpLifeCycles = new List<Http_Life_Cycle__c>();

        Http_Event__e event;

        for (Integer i = 0; i < events.size(); i++) {
            if (Math.mod(i, 200) == 0) {
                EventBus.TriggerContext.currentContext().setResumeCheckpoint(event.ReplayId);
            }

            event = events[i];

            httpLifeCycles.add(new Http_Life_Cycle__c(
                    Request_Body__c = event.Request_Body__c,
                    Request_Header__c = event.Request_Header__c,
                    Response_Body__c = event.Response_Body__c,
                    Response_Header__c = event.Response_Header__c,
                    Status_Code__c = event.Status_Code__c,
                    Url__c = event.Url__c
            ));
        }
        insert httpLifeCycles;
    }
}