force-app/main/default/objects/Http_Event__e/Http_Event__e.object-meta.xml
<CustomObject>
    <label>Http Event</label>
    <pluralLabel>Http Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Http_Life_Cycle__c/Http_Life_Cycle__c.object-meta.xml
<CustomObject>
    <label>Http Life Cycle</label>
    <nameField>
        <label>Http Life Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Http Life Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Http_Life_Cycle__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Http_Life_Cycle__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/HttpEventTriggerHandlerTest.cls
/**
 * Created by AntonAntoniuk on 25.09.2019.
 */

@IsTest
private class HttpEventTriggerHandlerTest {
    @IsTest
    static void testBehavior() {
        List<Http_Event__e> events = new List<Http_Event__e>();

        for (Integer i = 0; i < 400; i++) {
            events.add(new Http_Event__e(
                    Request_Body__c = 'Request_Body__c' + i,
                    Request_Header__c = 'Request_Header__c' + i,
                    Response_Body__c = 'Response_Body__c' + i,
                    Response_Header__c = 'Response_Header__c' + i,
                    Status_Code__c = i,
                    Url__c = 'Url__c' + i
            ));
        }

        Test.startTest();
        List<Database.SaveResult> results = EventBus.publish(events);
        Test.stopTest();

        List<Http_Life_Cycle__c> httpLifeCycles = [
                SELECT
                        Request_Body__c, Request_Header__c, Response_Body__c,
                        Response_Header__c, Status_Code__c, Url__c
                FROM Http_Life_Cycle__c
        ];

        System.assertEquals(httpLifeCycles.size(), 400);
        for (Integer i = 0; i < 400; i++) {
            System.assert(results[i].isSuccess());
        }
    }
}