force-app/main/default/objects/Remove_Job__c/Remove_Job__c.object-meta.xml
<CustomObject>
    <label>Remove Job</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Remove Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remove Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remove_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckJobStatus.cls
/**
 * Created by AntonAntoniuk on 20.09.2019.
 */

public with sharing class CheckJobStatus implements Schedulable {

    public void execute(SchedulableContext param1) {
        DropBoxConnection dropBox = new DropBoxConnection();
        List<Remove_Job__c> openJobs = [
                SELECT Id, JobId__c, Error_Message__c
                FROM Remove_Job__c
                WHERE Status__c = 'New'
        ];

        Map<String, List<String>> resultMessage;
        for (Remove_Job__c job : openJobs) {
            resultMessage = dropBox.checkDeletedStatus(job.JobId__c);
            if (resultMessage != null) {
                job.Status__c = String.valueOf(resultMessage.get('result')[0]);
                if (job.Status__c == 'Failed') {
                    job.Error_Message__c = 'ERROR! Some files has not been deleted in DropBox, please pay attention!';
                    if (resultMessage.get('successFiles') != new List<String>()) {
                        job.Error_Message__c += ' But this files has been deleted: ' + resultMessage.get('successFiles');
                    }
                }
            }
        }
        update openJobs;
    }
}