force-app/main/default/objects/Product2/fields/File_Id__c.field-meta.xml
<CustomField>
    <fullName>File_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>File Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemManagementComponentController.cls
/**
 * Created by AntonAntoniuk on 20.10.2019.
 */

public with sharing class ItemManagementComponentController {

    @AuraEnabled(Cacheable=true)
    public static List<Product2> getItems(String recordId) {
        List<PricebookEntry> pricebookEntries = [
                SELECT Product2Id
                FROM PricebookEntry
                WHERE Pricebook2Id = :Id.valueOf(recordId)
        ];

        Set<Id> pricebookEntriesProdIds = new Set<Id>();
        for (PricebookEntry pricebookEntry : pricebookEntries) {
            pricebookEntriesProdIds.add(pricebookEntry.Product2Id);
        }

        return [
                SELECT Name, Price__c, Status__c, ProductCode, Family, File_Id__c
                FROM Product2
                WHERE Id IN :pricebookEntriesProdIds
        ];
    }
}