force-app/main/default/objects/Product2Cache__c/Product2Cache__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Product2Cache</label>
</CustomObject>

force-app/main/default/objects/Product2Cache__c/fields/isCacheTemporraryLink__c.field-meta.xml
<CustomField>
    <fullName>isCacheTemporraryLink__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isCacheTemporraryLink</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DropBoxFileLinkFabricTest.cls
/**
 * Created by AntonAntoniuk on 24.09.2019.
 */

@IsTest
private class DropBoxFileLinkFabricTest {
    @IsTest
    static void defaultConnectionTest() {
        Test.setMock(HttpCalloutMock.class, new DropBoxConnectionTestMock());
        Product2Cache__c testCacheSettings = new Product2Cache__c(
                Name = 'Product2FileUrl',
                isCacheTemporraryLink__c = false);
        insert testCacheSettings;

        Test.startTest();
        DropBoxFileLinkFabric fabric = new DropBoxFileLinkFabric();
        DropBoxConnectionImpl connection = (DropBoxConnectionImpl) fabric.getDropBoxConnector();
        String result = connection.getDownloadLink('/Document.docx');
        Test.stopTest();

        System.assertEquals('https://dl.dropboxusercontent.com/apitl/1/Doc', result);
    }

    @IsTest
    static void proxyConnectionTest() {
        Test.setMock(HttpCalloutMock.class, new DropBoxConnectionTestMock());
        Product2Cache__c testCacheSettings = new Product2Cache__c(
                Name = 'Product2FileUrl',
                isCacheTemporraryLink__c = true);
        insert testCacheSettings;

        Test.startTest();
        DropBoxFileLinkFabric fabric = new DropBoxFileLinkFabric();
        DropBoxConnectionCachedProxy connectionProxy = (DropBoxConnectionCachedProxy) fabric.getDropBoxConnector();
        connectionProxy.cache = (CacheController) Test.createStub(CacheController.class, new MockProvider());
        String result = connectionProxy.getDownloadLink('/Document.docx');
        Test.stopTest();

        System.assertEquals('https://dl.dropboxusercontent.com/apitl/1/Doc', result);

    }

    private class DropBoxConnectionTestMock implements HttpCalloutMock {

        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            if (request.getBody() == '{\"path\": \"/Document.docx\"}') {
                response.setStatusCode(200);
                response.setBody('{"metadata": {}, "link": "https://dl.dropboxusercontent.com/apitl/1/Doc"}');
            } else {
                response.setStatusCode(409);
                response.setBody('Something went wrong!');
            }
            return response;
        }
    }
}