force-app/main/default/objects/Product2Cache__c/Product2Cache__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Product2Cache</label>
</CustomObject>

force-app/main/default/objects/Product2Cache__c/fields/isCacheTemporraryLink__c.field-meta.xml
<CustomField>
    <fullName>isCacheTemporraryLink__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isCacheTemporraryLink</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DropBoxFileLinkFabric.cls
/**
 * Created by AntonAntoniuk on 17.09.2019.
 */

public with sharing class DropBoxFileLinkFabric {

    @TestVisible
    private DropBoxConnection dropBox = new DropBoxConnection();

    public String getLinkForRecord(String fileId) {
        Product2Cache__c product2CacheSettings = Product2Cache__c.getAll().get('Product2FileUrl');
        String link;
        if (product2CacheSettings.isCacheTemporraryLink__c) {
            link = new DropBoxConnectionCachedProxy(new DropBoxConnection()).getDownloadLink(fileId);
        } else {
            link = dropBox.getDownloadLink(fileId);
        }
        return link;
    }
}